# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170121_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='purchase_value',
        ),
        migrations.AddField(
            model_name='item',
            name='sell_value',
            field=models.IntegerField(default=0),
        ),
    ]
