# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170801_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
            preserve_default=False,
        ),
    ]
