# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170801_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='-stone', max_length=140),
            preserve_default=False,
        ),
    ]
