# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
