# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True, default="Hi! I haven't edited my about section.", null=True),
        ),
    ]
