# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170806_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_value_coins',
            field=models.IntegerField(default=0),
        ),
    ]
