# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-10 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0052_remove_box_count'),
        ('core', '0013_item_purchase_value_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='associated_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon'),
        ),
    ]
