# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='overarching_category',
            field=models.CharField(default=0, max_length=56),
            preserve_default=False,
        ),
    ]
