# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
