# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20161109_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='last_viewed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
