# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20161109_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
    ]
