# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20161109_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
