# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='secondary_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
