# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20170115_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ehp',
            field=models.IntegerField(default=5500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evo_item',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evo_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='percent_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='rate',
            field=models.CharField(default='medium slow', max_length=24),
            preserve_default=False,
        ),
    ]
