# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20170115_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='percent_male',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
