# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20170115_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ehp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
