# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_auto_20170115_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
