# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemon_evo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evo_on_trade',
            field=models.BooleanField(default=False),
        ),
    ]
