# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0007_pokemon_evo_on_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatched', models.BooleanField(default=False)),
                ('exp', models.IntegerField(default=0)),
                ('happiness', models.IntegerField(default=0)),
                ('gender', models.BooleanField()),
                ('nature', models.CharField(max_length=24)),
                ('shiny', models.BooleanField(default=False)),
                ('held_item', models.CharField(blank=True, max_length=140, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon')),
            ],
        ),
    ]
