# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_auto_20170116_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='total_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
