# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0014_interaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('wallpaper', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='adopt',
            name='box_x_coord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopt',
            name='box_y_coord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adopt',
            name='boxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='pokemon',
            field=models.ManyToManyField(to='pokedex.Adopt'),
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
