# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0015_auto_20170117_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='box_x_coord',
            new_name='box_pos',
        ),
        migrations.RemoveField(
            model_name='adopt',
            name='box_y_coord',
        ),
        migrations.AlterField(
            model_name='box',
            name='pokemon',
            field=models.ManyToManyField(blank=True, to='pokedex.Adopt'),
        ),
    ]
