# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0018_auto_20170121_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='rarity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
