# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0021_auto_20170122_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
