# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0022_auto_20170122_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('number', models.IntegerField()),
                ('primary_type', models.CharField(max_length=24)),
                ('secondary_type', models.CharField(blank=True, max_length=24, null=True)),
                ('rarity', models.IntegerField(blank=True, null=True)),
                ('evo_item', models.CharField(blank=True, max_length=24, null=True)),
                ('evo_level', models.IntegerField(blank=True, null=True)),
                ('evo_on_trade', models.BooleanField(default=False)),
                ('evo', models.IntegerField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=24, null=True)),
                ('percent_male', models.IntegerField(blank=True, null=True)),
                ('ehp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
