# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0025_hunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
