# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0027_hunt_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='hatched',
            field=models.IntegerField(default=0),
        ),
    ]
