# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0028_hunt_hatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='chance',
        ),
    ]
