# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0029_remove_hunt_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='wallpaper',
            field=models.CharField(default='f3d054', max_length=6),
        ),
    ]
