# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0030_auto_20170802_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
