# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-04 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0031_box_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='beauty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopt',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopt',
            name='cute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopt',
            name='smart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adopt',
            name='tough',
            field=models.IntegerField(default=0),
        ),
    ]
