# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-04 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0032_auto_20170803_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='berry',
            field=models.BooleanField(default=False),
        ),
    ]
