# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0035_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='gts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='seen_by_reciever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='seen_by_sender',
            field=models.BooleanField(default=True),
        ),
    ]
