# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0036_auto_20170806_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='recieving_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
