# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0037_trade_recieving_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='seen_by_reciever',
            new_name='seen_final',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='seen_by_sender',
        ),
        migrations.AddField(
            model_name='trade',
            name='seen_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='seen_trade',
            field=models.BooleanField(default=False),
        ),
    ]
