# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0038_auto_20170806_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
