# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0039_trade_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='complete',
        ),
    ]
