# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0040_remove_trade_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
