# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0042_adopt_ready_to_evo_by_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
