# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0044_adopt_daycare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='happiness',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
