# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-07 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0045_auto_20170806_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='happiness',
            field=models.FloatField(default=0),
        ),
    ]
