# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0046_auto_20170807_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_stat', models.CharField(blank=True, max_length=24, null=True)),
                ('requested_stat_value', models.IntegerField(blank=True, null=True)),
                ('requested_happiness', models.IntegerField(blank=True, null=True)),
                ('date_assigned', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='PD', max_length=24)),
                ('payment_amount', models.IntegerField()),
                ('requested_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
