# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokedex', '0047_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_pokemon_rarity', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='date_assigned',
            new_name='date_accepted',
        ),
        migrations.AddField(
            model_name='contract',
            name='difficulty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
