# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0049_remove_potentialcontract_requested_pokemon_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='completed',
        ),
    ]
