# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0050_remove_contract_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='held_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_item', to='core.Item'),
        ),
    ]
