# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0055_adopt_box_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
