# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0061_daycareegg'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='daycare_adopt',
            field=models.BooleanField(default=False),
        ),
    ]
