# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm',
            name='parent_pm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pm.PM'),
            preserve_default=False,
        ),
    ]
