# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20170811_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm',
            name='parent_pm',
        ),
    ]
